### ISSUE TITLE
Mutation-Based Data Frame: Reshape data frame such that location and mutations are both represented in feature columns

### ISSUE THREAD

**Issue by ferdinsa** [katyaputintseva/ubird#10]

**Comment by ferdinsa** [comment]
Testing criteria: take random rows of the obtained dataframe and check that the information from the dataframe is compatible with the original datasheets.

**Comment by BielStela** [comment]
@ferdinsa Be carefull with pd.drop_duplicates() if you try to generate the categorical columns with pd.get_dummies()  because you'll run out of memory and your laptop will be angry at you.
