### ISSUE TITLE
Optimize the formation of sparse matrix out of the raw data

### ISSUE THREAD

**Issue by tiavlovskiegor24** [katyaputintseva/ubird#20]

**Comment by tiavlovskiegor24** [comment]
https://github.com/katyaputintseva/ubird/blob/Egor/Creating%20and%20saving%20sparse%20feature%20matrix%20and%20target%20values%20to%20file.ipynb

The approach outlined in this notebook gives the following:

Creating sparse matrix from raw data: 0.57 seconds
Writing sparse matrix to csv:                1.61 seconds
Reading sparse matrix from csv:           2.23 seconds

Everything is done with minimum memory requirements. 
I am sure there are even more efficient ways but this should do for our purposes.

**Comment by BielStela** [comment]
@tiavlovskiegor24 this is amazing Egor.  Thank you!
can you push it to the Master branch?

**Comment by tiavlovskiegor24** [comment]
Alright so now I create and store our matrix and target values in csv format.

Here is the annotated ipython notebook for constructing sparse matrix from raw data:

https://github.com/katyaputintseva/ubird/blob/Egor/Creating%20and%20saving%20sparse%20feature%20matrix%20and%20target%20values%20to%20file.ipynb

There are 5 csv files overall:
target_values - brightness values and their std 
col_names - mutation names corresponding to our columns
indices - matrix column indices locations where entries are non-zero.
indptr - ranges for each row in indices
shape - shape of our sparse matrix

I am not storing data array for our matrix because our entries are all "1".

In this file is the python codes for writing and reading our sparse matrix to and from csv files:
https://github.com/katyaputintseva/ubird/blob/Egor/write_read_sparse_csr.py
