### ISSUE TITLE
Write up the code for uploading sparse matrix into MongoDB database

### ISSUE THREAD

**Issue by tiavlovskiegor24** [katyaputintseva/ubird#21]

**Comment by tiavlovskiegor24** [comment]
Guys I don't quite understand why do we need MongoDB at all if we are working with a single file (our sparse matrix)? I though such databases are used when results from a lot of files has to be aggregated and processed simultaneously. 

It would have made sense if we combined datasets from multiples experiments, but in our case we are processing the results of a single experiment, right?

**Comment by katyaputintseva** [comment]
@tiavlovskiegor24 Right, we discussed this today as well. MongoDB doesn't really seem appropriate in our case. I think, we can drop this issue
