### ISSUE TITLE
Research Keras: is it possible to extract weights and store the obtained model?

### ISSUE THREAD

**Issue by BielStela** [katyaputintseva/ubird#26]
testing criteria: take a bit of time, if unwieldy, stop explo

**Comment by BielStela** [comment]
examine the network architecture in the paper

**Comment by tiavlovskiegor24** [comment]
https://keras.io/

**Comment by BielStela** [comment]
well, there is a way store the model in Keras. It's: **model.save_weights('file_name.h5')**
unbelievable.
