### ISSUE TITLE
Come up with a way to store sparse matrices.

### ISSUE THREAD

**Issue by katyaputintseva** [katyaputintseva/ubird#7]

**Comment by ferdinsa** [comment]
Testing criteria : perform a very simple classifier on both the full sparse matrix and the condensed version and check results.

**Comment by tiavlovskiegor24** [comment]
Alright so I played around with compressed sparse column (row) matrices (mostly during NLA project).  And I checked that all sklearn estimators eat these matrix representations with pleasure. 

Not sure about TensorFlow yet!

**Comment by tiavlovskiegor24** [comment]
So, Tensor flow has a format for sparse tensors
https://www.tensorflow.org/versions/r0.11/api_docs/python/sparse_ops.html

**Comment by tiavlovskiegor24** [comment]
So we successfully converted our matrix into csr format, saving a lot of storage space.

Once we start using tensorflow I will take care of using sparse tensor format
